%将系统函数化为分子分母形式
k=256;
num=[0,0,1,1];
den=[1,-1,0,0];
w=0:pi/k:pi;%数字频率
	h=freqz(num,den,w);%返回系统频率响应
	subplot(2,2,1);
	plot(w/pi,real(h));grid%归一化频率
	title('实部')
	xlabel('\omega/\pi');ylabel('幅度')
	subplot(2,2,2);
	plot(w/pi,imag(h));grid
	title('虚部')
	xlabel('\omega/\pi');ylabel('Amplitude')
	subplot(2,2,3);
	plot(w/pi,abs(h));grid
	title('幅度谱')
	xlabel('\omega/\pi');ylabel('幅值')
	subplot(2,2,4);
	plot(w/pi,angle(h));grid
	title('相位谱')
		xlabel('\omega/\pi');ylabel('弧度')
