%使用filter函数进行线性卷积 
% 线性卷积结果长度为i+j-1 (0~i+j-2) 至少要补11个零
%下面的代码是补充11个零的结果 可以看到刚好能够完成全部卷积
h = [1 4 2 3 2 1 -2 1 0 -4 0 3];	% impulse response     i=12
x = [1 -2 3 -4 3 2 1 2];		% input sequence		 j=8
n = 0:18;
x1 = [x zeros(1,11)];			%补11个零值
y1 = filter(h,1,x1);
stem(n,y1);
xlabel('Time index n'); ylabel('Amplitude');
title('Output Generated by Filtering'); grid 